apiVersion: v2
description: A Helm chart for installing the jetstack/cert-manager.
name: cert-manager
icon: https://raw.githubusercontent.com/cert-manager/community/4d35a69437d21b76322157e6284be4cd64e6d2b7/logo/logo-small.png
keywords:
  - cert-manager
  - kube-lego
  - letsencrypt
  - tls
version: 1.18.3
appVersion: 1.18.2
maintainers:
  - name: ivogoman
  - name: kengou
dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.18.4
