# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

operator:
  enabled: true

kafka:
  enabled: true
  replicas: 1
  config:
    offsets.topic.replication.factor: 1
    transaction.state.log.replication.factor: 1
    transaction.state.log.min.isr: 1
    default.replication.factor: 1
    min.insync.replicas: 1
  storage:
    type: ephemeral
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  metricsEnabled: true

entityOperator:
  enabled: true

monitoring:
  enabled: true

topics:
  logs:
    replicas: 1  # Single replica for test
    minInsyncReplicas: 1  # Single broker

  audit:
    replicas: 1  # Single replica for test
    minInsyncReplicas: 1  # Single broker

gatewayLogs:
  enabled: true
  brokerEndpoint: kafka-kafka-bootstrap.kafka.svc:9092
  collectorImage:
    repository: ghcr.io/cloudoperators/opentelemetry-collector-contrib
    tag: "cacb425"
  openSearchLogs:
    endpoint: test-endpoint
    index: test-index
    failover_username_a: test-username
    failover_password_a: test-password
