{{- if .Values.thanos.query.tls.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls
  labels:
    {{- include "plugin.labels" . | nindent 4 }}
    {{- include "thanos.labels" . | nindent 4 }}
data:
  ca.crt: {{ required ".Values.thanos.query.tls.data.caCert missing" .Values.thanos.query.tls.data.caCert | b64enc | quote }}
  tls.crt: {{ required ".Values.thanos.query.tls.data.tlsCert missing"  .Values.thanos.query.tls.data.tlsCert | b64enc | quote }}
  tls.key: {{ required ".Values.thanos.query.tls.data.tlsKey missing" .Values.thanos.query.tls.data.tlsKey | b64enc | quote }}
{{- end }}
