# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
description: Automatic onboarding of Gardener Shoots to Greenhouse
type: application
name: shoot-grafter
version: 0.1.8
appVersion: "sha-b590d69ade55d8ba16a1fe2bc1e19e61dc2702e6@sha256:26f4453ab1727d9c21af94ae73fa9331c89a47f6b1f3fecb17612ff058e12a1c"
keywords:
- operator
- gardener 
- greenhouse
maintainers:
  - name: ivogoman
  - name: uwe-mayer


