apiVersion: v2
name: perses
description: A Helm chart for Perses
icon: https://avatars.githubusercontent.com/u/77209215?s=200&v=4
type: application
version: 0.14.0
maintainers:
  - name: richardtief
  - name: ibakshay
annotations:
  "helm.sh/validateValues": "false"
keywords:
  - monitoring
  - metric
  - dashboarding
  - prometheus
dependencies:
  - name: perses
    repository: https://perses.github.io/helm-charts
    version: 0.14.0
