{{- if .Values.gatewayLogs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: logs-gateway-auth
  labels:
  {{- include "plugin.labels" . | nindent 4 }}
data:
   failover_username_a: {{ .Values.gatewayLogs.openSearchLogs.failover_username_a | b64enc | quote }}
   failover_password_a: {{ .Values.gatewayLogs.openSearchLogs.failover_password_a | b64enc | quote }}
{{- end }}
