# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: audit-logs
description: OpenTelemetry Collector Helm chart for audit-logs
icon: https://raw.githubusercontent.com/cncf/artwork/a718fa97fffec1b9fd14147682e9e3ac0c8817cb/projects/opentelemetry/icon/color/opentelemetry-icon-color.png
type: application
version: 0.0.14
maintainers:
- name: olandr
- name: kuckkuck
- name: timojohlo
sources:
- https://github.com/cloudoperators/greenhouse-extensions
