{{- if .Values.thanosParquetGateway.serve.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- include "thanosParquetGateway.annotations" (dict
        "base" .Values.thanosParquetGateway.serve.annotations
        "service" .Values.thanosParquetGateway.serve.serviceAnnotations
      ) | indent 2 }}
  labels:
    {{- include "plugin.labels" . | nindent 4 }}
    {{- include "thanosParquetGateway.labels" . | nindent 4 }}
    {{- if .Values.thanosParquetGateway.serve.serviceLabels }}
    {{- toYaml .Values.thanosParquetGateway.serve.serviceLabels | nindent 4 }}
    {{- end }}
  name: {{ include "release.name" . }}-serve
spec:
  ports:
  - name: grpc
    port: 19091
    protocol: TCP
    targetPort: grpc
  - name: http
    port: 19090
    protocol: TCP
    targetPort: http
  - name: health
    port: 6060
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/managed-by: {{ include "release.name" . }}
    app.kubernetes.io/name: serve
{{- end }}
