{{- if and .Values.thanos.ruler.enabled .Values.thanos.ruler.alertRelabelConfigs }}
apiVersion: v1
kind: Secret
metadata:
  name: thanos-ruler-{{ include "release.name" . }}-alert-relabel-config
  labels:
    {{- include "plugin.labels" . | nindent 4 }}
    {{- include "thanos.labels" . | nindent 4 }}
    {{- if .Values.thanos.ruler.labels }}
    {{- toYaml .Values.thanos.ruler.labels | nindent 4 }}
    {{- end }}
data:
  alert-relabel-configs.yaml: {{ tpl (toYaml .Values.thanos.ruler.alertRelabelConfigs) . | b64enc | quote }}
{{- end }}