# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

auditLogs:
  openSearchLogs:
    failover_username_a: testusera
    failover_password_a: passworda
    failover_username_b: testuserb
    failover_password_b: passwordb
    endpoint: test-endpoint
    index: test
  elastic:
      enabled: true
      endpoint: test
      tls:
        crt: testcrt
        key: testkey
      labels:
        - action: insert
          key: testkey
          value: testvalue
        - action: insert
          key: testkey
          value: testvalue
  cluster: test
  region: test
