# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
description: Automatic onboarding of Gardener Shoots to Greenhouse
type: application
name: shoot-grafter
version: 0.2.1
appVersion: "v0.2.0"
keywords:
- operator
- gardener 
- greenhouse
maintainers:
  - name: ivogoman
  - name: uwe-mayer


