# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
description: Automatic onboarding of Gardener Shoots to Greenhouse
type: application
name: shoot-grafter
version: 0.1.11
appVersion: "sha-66484e77a7c87fed3219435186e81ac138299970"
keywords:
- operator
- gardener 
- greenhouse
maintainers:
  - name: ivogoman
  - name: uwe-mayer


