# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

replicaCount: 1

image:
  registry: ghcr.io/cloudoperators
  repository: shoot-grafter
  pullPolicy: IfNotPresent

monitoring:
  labels:
    plugin: kube-monitoring
