{{- if .Values.siem.enabled }}
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

{{- range $userKey, $userData := .Values.siem.usersCredentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $userKey | lower }}-credentials
  labels:
    {{- include "opensearch.labels" $ | nindent 4 }}
type: Opaque
data:
  username: {{ default $userKey $userData.username | b64enc }}
  password: {{ $userData.password | b64enc }}
{{- end }}
{{- end }}
