{{/* 
SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: shoot-grafter
  namespace: {{ .Release.Namespace }}
