{{/* 
SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: shoot-grafter-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: shoot-grafter
spec:
  type: ClusterIP
  selector:
    app: shoot-grafter
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
