# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

image:
  registry: ghcr.io
  repository: cloudoperators/absent-metrics-operator
  tag: "edge"

promRuleName: "{{\"{{\"}} index .metadata.labels \"plugin\" {{\"}}\"}}"

labels: {}

rules:
  labels: {}