# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: kafka
version: 0.1.2
description: A Helm chart for Apache Kafka using the Strimzi Kafka Operator
type: application
maintainers:
- name: timojohlo
- name: kuckkuck
- name: joluc
home: https://github.com/cloudoperators/greenhouse-extensions/tree/main/kafka
sources:
  - https://github.com/strimzi/strimzi-kafka-operator
appVersion: 3.9.0
dependencies:
  - name: strimzi-kafka-operator
    alias: operator
    repository: https://strimzi.io/charts/
    version: 0.50.0
    condition: operator.enabled
