# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.oauth2proxy.enabled }}
{{- $fullName := include "oauth2-proxy.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  {{- end }}
  name: {{ $fullName }}
spec:
  ingressClassName: nginx
  rules:
  - host: auth-proxy.{{ required ".domain missing" $.Values.domain }}
    http:
      paths:
      - backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
        path: /oauth2
        pathType: Prefix
  tls:
  - hosts:
    - auth-proxy.{{ required ".domain missing" $.Values.domain }}
    secretName: {{ $fullName }}-tls
{{- end }}
