# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: absent-metrics-operator.alerts
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  groups:
  - name: liveness.alerts
    rules:
      - alert: AbsentMetricsOperatorReconciliationFailure
        # NOTE: Reconciliation happens every 5 minutes (300 seconds). To prevent alerts from going in and out of the PENDING state for every reconciliation loop, the threshold must be slightly bigger than 300 seconds. We choose 600 seconds (10 minutes).
        expr: sum(time() - absent_metrics_operator_successful_reconcile_time) by (prometheusrule_namespace, prometheusrule_name) > 600
        for: 5m
        labels:
          {{- with .Values.rules.labels }}
          {{ . | toYaml | nindent 10 }}
          {{- end }}
          severity: info
        annotations:
          summary: "Absent Metrics Operator cannot scrape `{{` {{ $labels.prometheusrule_namespace }}`}}`/ `{{` {{ $labels.prometheusrule_name }}`}}`"
          description: >
            The absent metrics operator has not done a successful scrape of `{{`{{ $labels.prometheusrule_namespace }}`}}`/`{{`{{ $labels.prometheusrule_name }}`}}`
            for more than 10 minutes. The `kubectl logs` for absent-metrics-operator in kube-monitoring namespace shoud contain additional info.
