kind: ServiceAccount
apiVersion: v1

metadata:
  name: absent-metrics-operator
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: absent-metrics-operator

rules:
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["prometheusrules"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: absent-metrics-operator

subjects:
  - kind: ServiceAccount
    namespace: "{{ .Release.Namespace }}"
    name: absent-metrics-operator
roleRef:
  kind: ClusterRole
  name: absent-metrics-operator
  apiGroup: rbac.authorization.k8s.io
