# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

thanosParquetGateway:
  serve:
    enabled: true
  convert:
    enabled: true


global:
  # -- Labels to apply to all resources
  # @default -- the chart will add some internal labels automatically
  commonLabels: {}

  # -- Overrides the registry globally for all images
  imageRegistry: null

image:
  # -- Thanos image repository
  repository: quay.io/thanos/thanos
  # -- Thanos image tag
  tag: v0.39.2
  # -- Thanos image pull policy
  pullPolicy: IfNotPresent

# -- GRPC-address used across the stack
# @default -- 0.0.0.0:10901
grpcAddress:

# -- HTTP-address used across the stack
# @default -- 0.0.0.0:10902
httpAddress:


# @ignored
# Init container to set permissions
initChownData:
  # initChownData container image
  image:
    # -- The Docker registry
    registry: docker.io
    repository: library/busybox
    tag: "stable"
    sha: ""




# @ignored
testFramework:
  # -- Enable Thanos test framework
  enabled: false
  image:
    registry: ghcr.io
    repository: cloudoperators/greenhouse-extensions-integration-test
    tag: v0.0.1
  imagePullPolicy: IfNotPresent

# @ignored
# Only used for TESTING !!! see test-values.yaml
# The kube-monitoring plugin is taking care of deploying the Prometheus Operator
# Thanos Plugin leverages it for its CI
ci:
  enabled: false
