# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

thanosParquetGateway:
  enabled: true
  serve:
    enabled: true
    bucket: "destination"
    endpoint: "host.docker.internal:9000"
    access_key: ""
    secret_key: ""
    volume:
      size:
      labels: []

  convert:
    enabled: true
    source:
      bucket: "source"
      endpoint: "host.docker.internal:9000"
      access_key: ""
      secret_key: ""
    destination:
      bucket: "destination"
      endpoint: "host.docker.internal:9000"
      access_key: ""
      secret_key: ""
    args:
      sortingLabels: ["__name__", "namespace"]



  initChownData:
    image:
      registry: docker.io
      repository: library/busybox
      tag: "stable"
      sha: ""

  image:
    repository: keppel.global.cloud.sap/ccloud/thanos-parquet-gateway
    tag: "20260123125451"
    pullPolicy: IfNotPresent

  # @ignored
  # Init container to set permissions
  initChownData:
    # initChownData container image
    image:
      # -- The Docker registry
      registry: docker.io
      repository: library/busybox
      tag: "stable"
      sha: ""

  objectStorageConfig:
    existingSecret: {}


  existingObjectStoreSecret:
    # -- Use existing objectStorageConfig Secret data and configure it to be used by Thanos Compactor and Store
    # https://thanos.io/tip/thanos/storage.md/#s3
    # @default -- {{ include "release.name" . }}-metrics-objectstore
    name:
    # -- Object store config file name
    # @default -- thanos.yaml
    configFile:




global:
  # -- Labels to apply to all resources
  # @default -- the chart will add some internal labels automatically
  commonLabels: {}

  # -- Overrides the registry globally for all images
  imageRegistry: null

# @ignored
# Init container to set permissions
initChownData:
  # initChownData container image
  image:
    # -- The Docker registry
    registry: docker.io
    repository: library/busybox
    tag: "stable"
    sha: ""




# @ignored
testFramework:
  # -- Enable Thanos test framework
  enabled: enable
  image:
    registry: ghcr.io
    repository: cloudoperators/greenhouse-extensions-integration-test
    tag: v0.0.1
  imagePullPolicy: IfNotPresent

# @ignored
# Only used for TESTING !!! see test-values.yaml
# The kube-monitoring plugin is taking care of deploying the Prometheus Operator
# Thanos Plugin leverages it for its CI
ci:
  enabled: false
