{{- if and .Values.alertmanager.alertmanager.enabled .Values.alertmanager.alertmanager.ingress.enabled .Values.global.caCert .Values.alertmanager.caCert }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $.Release.Namespace }}-ca-bundle
  labels:
{{- include "kube-prometheus-stack.labels" . | indent 4 }}
data:
  ca.crt: {{ printf "%s%s" .Values.global.caCert .Values.alertmanager.caCert | b64enc | quote }}
{{- end }}
