{{- if .Values.alertmanager.certManager.enabled -}}
{{- if not .Values.alertmanager.certManager.issuerRef -}}
# Create a selfsigned Issuer in order to create a root CA certificate for the org
# signing alertmanager serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: '{{ .Release.Namespace }}-alertmanager-issuer'
  labels:
{{- include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  selfSigned: {}
---
# Generate a CA Certificate used to sign certificates for the alertmanager
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: '{{ .Release.Namespace }}-alertmanager-root-cert'
  labels:
{{- include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  secretName: tls-alertmanager-{{ .Release.Namespace  }}-root-ca
  duration: {{ .Values.alertmanager.certManager.rootCert.duration | default "43800h0m0s" | quote }}
  issuerRef:
    name: {{ .Release.Namespace }}-alertmanager-issuer
  commonName: "ca.prometheus.greenhouse"
  isCA: true
---
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: '{{ .Release.Namespace }}-alertmanager-root-issuer'
  labels:
{{- include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  ca:
    secretName: tls-alertmanager-{{ .Release.Namespace  }}-root-ca
{{- end }}
---
# generate a server certificate for the alertmanager to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager-{{ .Release.Namespace }}-cert
  labels:
{{- include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  secretName: tls-alertmanager-{{ .Release.Namespace }}
  duration: {{ .Values.alertmanager.certManager.admissionCert.duration | default "8760h0m0s" | quote }}
  issuerRef:
    {{- if .Values.alertmanager.certManager.issuerRef }}
    {{- toYaml .Values.alertmanager.certManager.issuerRef | nindent 4 }}
    {{- else }}
    name: {{ .Release.Namespace }}-alertmanager-root-issuer
    {{- end }}
  dnsNames:
  - {{ include "kube-prometheus-stack.fullname" . }}
  - {{ include "kube-prometheus-stack.fullname" . }}.{{ .Release.Namespace }}
  - {{ include "kube-prometheus-stack.fullname" . }}.{{ .Release.Namespace }}.svc
{{- if .Values.global.greenhouse.baseDomain }}
  - {{ printf "*.%s" .Values.global.greenhouse.baseDomain | quote }}
{{- end }}
{{- if and .Values.alertmanager.alertmanager.ingress.enabled .Values.alertmanager.alertmanager.ingress.hosts }}
{{ toYaml .Values.alertmanager.alertmanager.ingress.hosts | indent 2 }}
{{- end }}
---
# generate a shared client certificate for prometheus to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-{{ .Release.Namespace }}-cert
  labels:
{{- include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  secretName: tls-prometheus-{{ .Release.Namespace }}
  duration: {{ .Values.alertmanager.certManager.admissionCert.duration | default "8760h0m0s" | quote }}
  issuerRef:
    {{- if .Values.alertmanager.certManager.issuerRef }}
    {{- toYaml .Values.alertmanager.certManager.issuerRef | nindent 4 }}
    {{- else }}
    name: {{ .Release.Namespace }}-alertmanager-root-issuer
    {{- end }}
  dnsNames:
  - {{ include "kube-prometheus-stack.fullname" . }}
  - {{ include "kube-prometheus-stack.fullname" . }}.{{ .Release.Namespace }}
  - {{ include "kube-prometheus-stack.fullname" . }}.{{ .Release.Namespace }}.svc
{{- if .Values.global.greenhouse.baseDomain }}
  - {{ printf "*.%s" .Values.global.greenhouse.baseDomain | quote }}
{{- end }}
{{- end -}}
